name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install # Atau sesuaikan dengan bahasa pemrograman yang Anda gunakan

      - name: Run script
        run: node your-script.js # Gantilah dengan nama dan perintah sesuai skrip Anda

      - name: Commit and push if changed
        run: |
          git config --local user.email "ronaldofirmansyah.30@gmail.com"
          git config --local user.name "Ronaldo-spec"
          git add README.md
          git commit -m "Update README with GitHub Stats"
          git push
